/**
 * Generators for the demo's two flat textures.
 *
 * Both are pure functions of their arguments, so the committed PNGs can be
 * regenerated byte-for-byte by pixel comparison in the test suite.
 *
 * Coordinate conventions
 *  - Images are row-major with row 0 at the **top**.
 *  - three.js flips textures vertically by default, so row 0 maps to the top of
 *    a sphere or cylinder, which is what both of these rely on.
 */

import {
  blendPixel,
  createImage,
  createRandom,
  fillRect,
  getPixel,
  hexColor,
  mixColors,
  randomInt,
  setPixel,
  type RgbaColor,
  type RgbaImage,
} from './png.ts';

export interface AssetDefinition {
  /** File name inside the texture directory. */
  readonly name: string;
  readonly generate: () => RgbaImage;
}

// --------------------------------------------------------------------- sky

export interface SkyGradientOptions {
  readonly width?: number;
  readonly height?: number;
}

/**
 * A vertical gradient for the sky dome.
 *
 * On a sphere the texture's vertical centre is the horizon, so the bright band
 * sits at 50% of the image with the zenith darkening above it and the (usually
 * occluded) nadir darkening below. The horizon carries a magenta cast, which is
 * what gives the night a cyberpunk glow without any extra geometry.
 */
export function generateSkyGradient(options: SkyGradientOptions = {}): RgbaImage {
  const width = options.width ?? 8;
  const height = options.height ?? 256;
  const image = createImage(width, height);

  // Row position (0 = zenith, 0.5 = horizon, 1 = nadir) mapped to a colour.
  const stops: { at: number; color: RgbaColor }[] = [
    { at: 0.0, color: hexColor('#04060d') },
    { at: 0.18, color: hexColor('#070c18') },
    { at: 0.34, color: hexColor('#101a33') },
    { at: 0.44, color: hexColor('#243056') },
    { at: 0.5, color: hexColor('#43325f') },
    { at: 0.56, color: hexColor('#221c3b') },
    { at: 0.68, color: hexColor('#121829') },
    { at: 0.82, color: hexColor('#0a0e1a') },
    { at: 1.0, color: hexColor('#06080f') },
  ];

  for (let row = 0; row < height; row += 1) {
    const position = row / (height - 1);
    const color = sampleGradient(stops, position);
    for (let column = 0; column < width; column += 1) {
      setPixel(image, column, row, color);
    }
  }

  return image;
}

function sampleGradient(stops: readonly { at: number; color: RgbaColor }[], position: number): RgbaColor {
  const first = stops[0] as { at: number; color: RgbaColor };
  const last = stops[stops.length - 1] as { at: number; color: RgbaColor };
  if (position <= first.at) return first.color;
  if (position >= last.at) return last.color;

  for (let index = 0; index < stops.length - 1; index += 1) {
    const a = stops[index] as { at: number; color: RgbaColor };
    const b = stops[index + 1] as { at: number; color: RgbaColor };
    if (position >= a.at && position <= b.at) {
      const span = b.at - a.at;
      const t = span === 0 ? 0 : (position - a.at) / span;
      return mixColors(a.color, b.color, t);
    }
  }
  return last.color;
}

// ---------------------------------------------------------- city backdrop

interface SkylineLayer {
  readonly color: RgbaColor;
  /** Building height as a fraction of the image height. */
  readonly minHeight: number;
  readonly maxHeight: number;
  /** Building width, in pixels. */
  readonly minWidth: number;
  readonly maxWidth: number;
  /** Probability that any one window is lit. */
  readonly litChance: number;
  readonly windowColor: RgbaColor;
  readonly windowSize: number;
  readonly windowGapX: number;
  readonly windowGapY: number;
  /** Probability of a rooftop beacon on a given building. */
  readonly beaconChance: number;
  readonly beaconColor: RgbaColor;
}

export interface CityBackdropOptions {
  readonly width?: number;
  readonly height?: number;
  readonly seed?: number;
}

/**
 * A layered night skyline, drawn far-to-near.
 *
 * Above the silhouette the alpha channel stays 0, so the gradient sky shows
 * through the gaps - which is the whole point of a flat backdrop.
 *
 * Buildings are packed edge to edge across the full width with the last one
 * clipped, so the texture wraps around a cylinder without a visible seam: the
 * wrap point just looks like two neighbouring buildings of different heights.
 */
export function generateCityBackdrop(options: CityBackdropOptions = {}): RgbaImage {
  const width = options.width ?? 2048;
  const height = options.height ?? 512;
  const random = createRandom(options.seed ?? 0x0c17b3a5);

  const image = createImage(width, height);

  // Far to near: distant layers are paler (atmospheric haze) and shorter, near
  // layers are darker silhouettes with the most lit windows.
  const layers: SkylineLayer[] = [
    {
      color: hexColor('#48587f'),
      minHeight: 0.3,
      maxHeight: 0.62,
      minWidth: 26,
      maxWidth: 74,
      litChance: 0.05,
      windowColor: hexColor('#a8c7ec'),
      windowSize: 2,
      windowGapX: 6,
      windowGapY: 7,
      beaconChance: 0.04,
      beaconColor: hexColor('#ffe2b0'),
    },
    {
      color: hexColor('#2e3b57'),
      minHeight: 0.18,
      maxHeight: 0.46,
      minWidth: 36,
      maxWidth: 104,
      litChance: 0.08,
      windowColor: hexColor('#ffc27a'),
      windowSize: 3,
      windowGapX: 8,
      windowGapY: 10,
      beaconChance: 0.06,
      beaconColor: hexColor('#ff9d5c'),
    },
    {
      color: hexColor('#1e2636'),
      minHeight: 0.1,
      maxHeight: 0.32,
      minWidth: 52,
      maxWidth: 140,
      litChance: 0.11,
      windowColor: hexColor('#58deff'),
      windowSize: 3,
      windowGapX: 9,
      windowGapY: 12,
      beaconChance: 0.09,
      beaconColor: hexColor('#ff4fa3'),
    },
  ];

  for (const layer of layers) {
    let x = 0;
    while (x < width) {
      const buildingWidth = Math.min(randomInt(random, layer.minWidth, layer.maxWidth), width - x);
      const buildingHeight = Math.round(
        height * (layer.minHeight + random() * (layer.maxHeight - layer.minHeight)),
      );
      const top = height - buildingHeight;

      fillRect(image, x, top, buildingWidth, buildingHeight, layer.color);
      drawWindows(image, random, layer, x, top, buildingWidth, buildingHeight);

      if (random() < layer.beaconChance && buildingWidth > 24) {
        const beaconX = x + Math.floor(buildingWidth / 2);
        fillRect(image, beaconX, top - 1, 2, 3, layer.beaconColor);
      }

      x += buildingWidth;
    }
  }

  // A faint single-pixel rim on the near silhouettes keeps the skyline crisp
  // against the sky at a distance, where the texture is minified.
  outline(image, hexColor('#39496e'));

  return image;
}

function drawWindows(
  image: RgbaImage,
  random: () => number,
  layer: SkylineLayer,
  buildingX: number,
  buildingTop: number,
  buildingWidth: number,
  buildingHeight: number,
): void {
  const size = layer.windowSize;
  // Leave a margin so windows do not sit on the building's edge.
  const inset = size + 3;
  if (buildingWidth < inset * 2 || buildingHeight < inset * 2) return;

  for (let y = buildingTop + inset; y + size <= buildingTop + buildingHeight - 2; y += layer.windowGapY) {
    for (let x = buildingX + inset; x + size <= buildingX + buildingWidth - 2; x += layer.windowGapX) {
      if (random() >= layer.litChance) continue;
      // Jitter the brightness so a lit block does not look like a solid slab.
      const brightness = 0.55 + random() * 0.45;
      const color: RgbaColor = {
        r: Math.round(layer.windowColor.r * brightness),
        g: Math.round(layer.windowColor.g * brightness),
        b: Math.round(layer.windowColor.b * brightness),
        a: 255,
      };
      fillRect(image, x, y, size, size, color);
    }
  }
}

/** Adds a one-pixel highlight along the top edge of every silhouette run. */
function outline(image: RgbaImage, color: RgbaColor): void {
  for (let y = 0; y < image.height; y += 1) {
    for (let x = 0; x < image.width; x += 1) {
      const here = getPixel(image, x, y);
      if (here.a === 0) continue;
      const above = y === 0 ? { r: 0, g: 0, b: 0, a: 0 } : getPixel(image, x, y - 1);
      if (above.a === 0) blendPixel(image, x, y, { ...color, a: 90 });
    }
  }
}

/**
 * Every texture the demo needs.
 *
 * Order matters only for the writer's log output.
 */
export const TEXTURES: readonly AssetDefinition[] = [
  { name: 'city-backdrop.png', generate: () => generateCityBackdrop() },
  { name: 'sky-gradient.png', generate: () => generateSkyGradient() },
];
